/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views.CuocHopManagerFrame;

import java.util.ArrayList;
import java.util.List;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

import java.awt.event.ActionEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

import Bean.MemOfMeeting;
import controllers.CuocHopManagerController.ChangeListMeetingAttendeeController;

/**
 *
 * @author minib
 */
public class ChangeListMeetingAttendeeJframe extends javax.swing.JFrame {

    private List<MemOfMeeting> listMember;
    private List<MemOfMeeting> listMemberTemp;
    private ChangeListMeetingAttendeeController controller;
    private JFrame parentJFrame;

     /**
     * Creates new form ChangeListMeetingAttendeeJframe
     * @param listMember
     * @param parentJFrame
     */
    public ChangeListMeetingAttendeeJframe(List<MemOfMeeting> listMember, JFrame parentJFrame) {
        initComponents();
        this.listMember = listMember;
        this.listMemberTemp = new ArrayList<>();
        this.listMemberTemp.addAll(listMember);
        this.parentJFrame = parentJFrame;
        this.controller = new ChangeListMeetingAttendeeController(this.listMemberTemp, addBtn, removeBtn, jTextField1, PeopleTableJpn, MemTableJpn);
        this.parentJFrame.setEnabled(false);
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                close();
            }
        });
    }
    
    private void close() {
        if (JOptionPane.showConfirmDialog(this, "Are you sure to close???", "confirm", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
            this.parentJFrame.setEnabled(true);
            dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        removeBtn = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        PeopleTableJpn = new javax.swing.JPanel();
        MemTableJpn = new javax.swing.JPanel();
        addBtn = new javax.swing.JButton();
        removeBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();

        removeBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        removeBtn.setText("<<");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        
        addBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        addBtn.setText(">>");
        
        removeBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        removeBtn.setText("<<");
        
        saveBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        saveBtn.setText("Lưu thay đổi ");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PeopleTableJpnLayout = new javax.swing.GroupLayout(PeopleTableJpn);
        PeopleTableJpn.setLayout(PeopleTableJpnLayout);
        PeopleTableJpnLayout.setHorizontalGroup(
            PeopleTableJpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PeopleTableJpnLayout.setVerticalGroup(
            PeopleTableJpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout MemTableJpnLayout = new javax.swing.GroupLayout(MemTableJpn);
        MemTableJpn.setLayout(MemTableJpnLayout);
        MemTableJpnLayout.setHorizontalGroup(
            MemTableJpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 339, Short.MAX_VALUE)
        );
        MemTableJpnLayout.setVerticalGroup(
            MemTableJpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PeopleTableJpn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 135, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(removeBtn)
                            .addComponent(addBtn))
                        .addGap(18, 18, 18)
                        .addComponent(MemTableJpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveBtn))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MemTableJpn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addBtn)
                        .addGap(38, 38, 38)
                        .addComponent(removeBtn)
                        .addGap(0, 226, Short.MAX_VALUE))
                    .addComponent(PeopleTableJpn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBtnActionPerformed
        this.listMember.clear();
        this.listMember.addAll(this.listMemberTemp);
        ThemMoiCuocHop themMoiCuocHop = (ThemMoiCuocHop)this.parentJFrame;
        themMoiCuocHop.setDataThanhVien();
        close();
    }//GEN-LAST:event_removeBtnActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MemTableJpn;
    private javax.swing.JPanel PeopleTableJpn;
    private javax.swing.JButton addBtn;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton removeBtn;
    // End of variables declaration//GEN-END:variables
}
