package views.NhanKhauManagerFrame;

import javax.swing.*;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;

import controllers.NhanKhauManagerController.KhaiTuController;
import models.KhaiTuModel;

public class KhaiTuJFrame extends javax.swing.JFrame {

    /**
     * Creates new form KhaiTuJFrame
     */
    private KhaiTuController controller;
    private JFrame parentJFrame = null;
    private KhaiTuModel khaiTuModel;

    private void setAble()
    {
        jTextArea1.setEnabled(true);
        JTextFieldGiayKhaiTu.setEnabled(true);
    }

    public KhaiTuJFrame(JFrame parentJFrame) {
        initComponents();
        this.parentJFrame = parentJFrame;
        this.controller = new KhaiTuController();
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        parentJFrame.setEnabled(false);

        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                close();
            }

        });
    }

    private void close() {
        if (JOptionPane.showConfirmDialog(this, "Are you sure to close??", "Confirm",
                JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
            this.parentJFrame.setEnabled(true);
            dispose();
        }
    }

    private boolean checkCMT(String cmt) {
        if (cmt.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số CMT", "Warning", JOptionPane.WARNING_MESSAGE);
            return false;
        } else {
            try {
                long temp = Long.parseLong(cmt);
                if (cmt.trim().length() != 9 && cmt.trim().length() != 12) {
                    throw new Exception("Sai dinh dang");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập đúng định dạng số CMT!", "Warning",
                        JOptionPane.WARNING_MESSAGE);
            }
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JLabelNguoiKhai = new javax.swing.JLabel();
        JSoCCCDNguoiKhai = new javax.swing.JTextField();
        JLabelGiayKhaiTu = new javax.swing.JLabel();
        JTextFieldGiayKhaiTu = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        JButtonNguoiKhai = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        JLabelNguoiChet = new javax.swing.JLabel();
        JSoCCCDNguoiChet = new javax.swing.JTextField();
        JButtonNguoiChet = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/checked.png"))); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/checked.png"))); // NOI18N
        jLabel3.setEnabled(false);
        jLabel8.setEnabled(false);



        JLabelNguoiKhai.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        JLabelNguoiKhai.setText("Số CMT người khai:");
        JSoCCCDNguoiKhai.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        JButtonNguoiKhai.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        JButtonNguoiKhai.setText("Check");
        JButtonNguoiKhai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonNguoiKhaiActionPerformed(evt);
            }
        });

        

        JLabelNguoiChet.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        JLabelNguoiChet.setText("Số CMT người chết:");
        JSoCCCDNguoiChet.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        JButtonNguoiChet.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        JButtonNguoiChet.setText("Check");
        JButtonNguoiChet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonNguoiChetActionPerformed(evt);
            }
        });

        JLabelGiayKhaiTu.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        JLabelGiayKhaiTu.setText("Số giấy khai tử:");
        JTextFieldGiayKhaiTu.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        JTextFieldGiayKhaiTu.setEnabled(false);

        JTextFieldGiayKhaiTu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                // JTextFieldGiayKhaiTuActionPerformed(evt);
            }
        });

        jButton2.setText("Xác nhận");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton3.setText("Hủy");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Ngày khai:");

        jDateChooser1.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Ngày chết:");

        jDateChooser2.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Lý do chết:");

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setEnabled(false);
        jScrollPane1.setViewportView(jTextArea1);


        

        

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                .addComponent(jButton3,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 80,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jButton2,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 80,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addGroup(jPanel1Layout
                                                                                        .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(jLabel4)
                                                                                        .addComponent(jLabel5))
                                                                                .addGap(51, 51, 51))
                                                                        .addGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                jPanel1Layout.createSequentialGroup()
                                                                                        .addComponent(JLabelGiayKhaiTu)
                                                                                        .addGap(18, 18, 18)))
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jDateChooser1,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                        .addComponent(JTextFieldGiayKhaiTu)
                                                                        .addComponent(jDateChooser2,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jLabel6)
                                                                .addGap(48, 48, 48)
                                                                .addComponent(jScrollPane1)))
                                                .addContainerGap())
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(JLabelNguoiKhai)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE)
                                                                .addComponent(JSoCCCDNguoiKhai,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 274,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(JLabelNguoiChet)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                        13, Short.MAX_VALUE)
                                                                .addComponent(JSoCCCDNguoiChet,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 274,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(JButtonNguoiKhai)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jLabel3))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(JButtonNguoiChet)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jLabel8)))
                                                .addGap(14, 14, 14)))));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(JLabelNguoiKhai, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(JSoCCCDNguoiKhai, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(JButtonNguoiKhai, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(JLabelNguoiChet, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(JSoCCCDNguoiChet, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(JButtonNguoiChet, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34,
                                        Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(JLabelGiayKhaiTu, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(JTextFieldGiayKhaiTu, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton2)
                                        .addComponent(jButton3))
                                .addContainerGap()));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JButtonNguoiKhaiActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_JButtonNguoiKhaiActionPerformed
        if (checkCMT(JSoCCCDNguoiKhai.getText())) {
            int idNhanKhau = this.controller.checkCMT(JSoCCCDNguoiKhai.getText());
            if (idNhanKhau > 0) {
                JOptionPane.showMessageDialog(this, "OK!!");
            } else {
                if (JOptionPane.showConfirmDialog(null,
                        "Không tìm thấy người có số CMT: " + JSoCCCDNguoiKhai.getText() + ". Thêm mới?", "Confirm",
                        JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION) {
                    AddNewPeopleJFrame addNewPeopleJFrame = new AddNewPeopleJFrame(this);
                    addNewPeopleJFrame.setLocationRelativeTo(null);
                    addNewPeopleJFrame.setResizable(false);
                    addNewPeopleJFrame.setVisible(true);
                }
            }
        }
    }// GEN-LAST:event_JButtonNguoiKhaiActionPerformed

    private void JTextFieldGiayKhaiTuActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_JTextFieldGiayKhaiTuActionPerformed
        
    }// GEN-LAST:event_JTextFieldGiayKhaiTuActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton3ActionPerformed
        close();
    }// GEN-LAST:event_jButton3ActionPerformed

    private void JButtonNguoiChetActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_JButtonNguoiChetActionPerformed
        if (checkCMT(JSoCCCDNguoiChet.getText())) {
            int idNhanKhau = this.controller.checkCMT(JSoCCCDNguoiChet.getText());
            if (idNhanKhau > 0) {
                JOptionPane.showMessageDialog(this, "OK!!");
                setAble();
            } else {
                if (JOptionPane.showConfirmDialog(null,
                        "Không tìm thấy người có số CMT: " + JSoCCCDNguoiChet.getText() + ". Thêm mới?", "Confirm",
                        JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION) {
                    AddNewPeopleJFrame addNewPeopleJFrame = new AddNewPeopleJFrame(this);
                    addNewPeopleJFrame.setLocationRelativeTo(null);
                    addNewPeopleJFrame.setResizable(false);
                    addNewPeopleJFrame.setVisible(true);
                }
            }
        }
    }// GEN-LAST:event_JButtonNguoiChetActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonNguoiKhai;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton JButtonNguoiChet;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel JLabelNguoiKhai;
    private javax.swing.JLabel JLabelGiayKhaiTu;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel JLabelNguoiChet;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField JSoCCCDNguoiKhai;
    private javax.swing.JTextField JTextFieldGiayKhaiTu;
    private javax.swing.JTextField JSoCCCDNguoiChet;
    private javax.swing.JTextField soCmtJtf;
    // End of variables declaration//GEN-END:variables
}
